import { User, Post, Notification } from '@/models/models';

export const users: User[] = [
    {
        id: '1',
        username: 'johndoe',
        profilePictureUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
        bio: 'Just a regular John Doe.',
        postsCount: 12,
    },
    {
        id: '2',
        username: 'janedoe',
        profilePictureUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
        bio: 'Lover of nature and art.',
        postsCount: 15,
    },
    {
        id: '3',
        username: 'alexsmith',
        profilePictureUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
        bio: 'Traveler. Photographer. Foodie.',
        postsCount: 20,
    },
    {
        id: '4',
        username: 'emilywhite',
        profilePictureUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
        bio: 'Coffee enthusiast and bookworm.',
        postsCount: 18,
    },
    {
        id: '5',
        username: 'michaelbrown',
        profilePictureUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
        bio: 'Tech geek and gamer.',
        postsCount: 22,
    },
    {
        id: '6',
        username: 'sarahgreen',
        profilePictureUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
        bio: 'Fitness coach and wellness blogger.',
        postsCount: 25,
    },
    {
        id: '7',
        username: 'davidlee',
        profilePictureUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
        bio: 'Musician and songwriter.',
        postsCount: 17,
    },
    {
        id: '8',
        username: 'laurabrown',
        profilePictureUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
        bio: 'Artist and designer.',
        postsCount: 19,
    },
    {
        id: '9',
        username: 'robertjohnson',
        profilePictureUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
        bio: 'Entrepreneur and blogger.',
        postsCount: 21,
    },
    {
        id: '10',
        username: 'oliviamartin',
        profilePictureUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
        bio: 'Food lover and chef.',
        postsCount: 16,
    },
];

export const posts: Post[] = [
    {
        id: '1',
        userId: '1',
        imageUrl: 'https://picsum.photos/id/1011/600/400',
        caption: 'Beautiful sunset over the hills!',
        likes: 150,
    },
    {
        id: '2',
        userId: '2',
        imageUrl: 'https://picsum.photos/id/1012/600/400',
        caption: 'A day at the beach.',
        likes: 200,
    },
    {
        id: '3',
        userId: '3',
        imageUrl: 'https://picsum.photos/id/1013/600/400',
        caption: 'Exploring the city lights.',
        likes: 175,
    },
    {
        id: '4',
        userId: '4',
        imageUrl: 'https://picsum.photos/id/1014/600/400',
        caption: 'My morning coffee routine.',
        likes: 220,
    },
    {
        id: '5',
        userId: '5',
        imageUrl: 'https://picsum.photos/id/1015/600/400',
        caption: 'Latest tech gadgets unboxing!',
        likes: 190,
    },
    {
        id: '6',
        userId: '6',
        imageUrl: 'https://picsum.photos/id/1016/600/400',
        caption: 'Workout tips for beginners.',
        likes: 250,
    },
    {
        id: '7',
        userId: '7',
        imageUrl: 'https://picsum.photos/id/1018/600/400',
        caption: 'New song release preview.',
        likes: 180,
    },
    {
        id: '8',
        userId: '8',
        imageUrl: 'https://picsum.photos/id/1019/600/400',
        caption: 'Artwork in progress.',
        likes: 210,
    },
    {
        id: '9',
        userId: '9',
        imageUrl: 'https://picsum.photos/id/1020/600/400',
        caption: 'Tips on starting your own business.',
        likes: 230,
    },
    {
        id: '10',
        userId: '10',
        imageUrl: 'https://picsum.photos/id/1021/600/400',
        caption: 'Delicious recipes coming soon!',
        likes: 160,
    },
    {
        id: '11',
        userId: '1',
        imageUrl: 'https://picsum.photos/id/1022/600/400',
        caption: 'Hiking adventures!',
        likes: 130,
    },
    {
        id: '12',
        userId: '2',
        imageUrl: 'https://picsum.photos/id/1023/600/400',
        caption: 'Nature photography.',
        likes: 205,
    },
    {
        id: '13',
        userId: '3',
        imageUrl: 'https://picsum.photos/id/1024/600/400',
        caption: 'Street food delights.',
        likes: 185,
    },
];

export const notifications: Notification[] = [
    {
        id: '1',
        type: 'like',
        postId: '1',
        userId: '2',
        message: 'janedoe liked your post.',
        createdAt: new Date('2023-10-01T10:00:00Z'),
    },
    {
        id: '2',
        type: 'comment',
        postId: '2',
        userId: '1',
        message: 'johndoe commented on your post.',
        createdAt: new Date('2023-10-02T11:30:00Z'),
    },
    {
        id: '3',
        type: 'like',
        postId: '3',
        userId: '4',
        message: 'emilywhite liked your post.',
        createdAt: new Date('2023-10-03T12:45:00Z'),
    },
    {
        id: '4',
        type: 'comment',
        postId: '4',
        userId: '3',
        message: 'alexsmith commented on your post.',
        createdAt: new Date('2023-10-04T14:15:00Z'),
    },
    {
        id: '5',
        type: 'like',
        postId: '5',
        userId: '6',
        message: 'sarahgreen liked your post.',
        createdAt: new Date('2023-10-05T15:25:00Z'),
    },
    {
        id: '6',
        type: 'comment',
        postId: '6',
        userId: '5',
        message: 'michaelbrown commented on your post.',
        createdAt: new Date('2023-10-06T16:35:00Z'),
    },
    {
        id: '7',
        type: 'like',
        postId: '7',
        userId: '8',
        message: 'laurabrown liked your post.',
        createdAt: new Date('2023-10-07T17:45:00Z'),
    },
    {
        id: '8',
        type: 'comment',
        postId: '8',
        userId: '7',
        message: 'davidlee commented on your post.',
        createdAt: new Date('2023-10-08T18:55:00Z'),
    },
    {
        id: '9',
        type: 'like',
        postId: '9',
        userId: '10',
        message: 'oliviamartin liked your post.',
        createdAt: new Date('2023-10-09T20:05:00Z'),
    },
    {
        id: '10',
        type: 'comment',
        postId: '10',
        userId: '9',
        message: 'robertjohnson commented on your post.',
        createdAt: new Date('2023-10-10T21:15:00Z'),
    },
    {
        id: '11',
        type: 'like',
        postId: '11',
        userId: '2',
        message: 'janedoe liked your post.',
        createdAt: new Date('2023-10-11T22:25:00Z'),
    },
    {
        id: '12',
        type: 'comment',
        postId: '12',
        userId: '1',
        message: 'johndoe commented on your post.',
        createdAt: new Date('2023-10-12T23:35:00Z'),
    },
    {
        id: '13',
        type: 'like',
        postId: '13',
        userId: '4',
        message: 'emilywhite liked your post.',
        createdAt: new Date('2023-10-13T08:45:00Z'),
    },
];

